name: Quality Gate - Lint, Format & Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Check for changed workflow files
        id: changed-workflows
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | grep '^.github/workflows/.*\.yml$' || true)
          echo "changed_files=$CHANGED" >> $GITHUB_OUTPUT

      - name: Run actionlint on changed workflow files
        if: steps.changed-workflows.outputs.changed_files != ''
        uses: rhysd/actionlint@main
        with:
          paths: ${{ steps.changed-workflows.outputs.changed_files }}
      - name: Run Prettier (check only)
        run: npx prettier --check .
      - name: Run ESLint
        run: npx eslint . --ext .ts,.js --plugin playwright

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Chromium only
        run: npx playwright install chromium --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
